#!/bin/sh

if [ ! -d ]; then
	mkdir /proc
fi
mount -t proc proc /proc

if [ ! -d /sys ]; then
	mkdir /sys
fi
mount -t sysfs sysfs /sys

if [ ! -d /dev ]; then
	mkdir /dev
fi
mount -t devtmpfs devtmpfs /dev 2>/dev/null || mount -t tmpfs tmpfs /dev

if [ -x /sbin/mdev ]; then
	echo /sbin/mdev > /proc/sys/kernel/hotplug
	mdev -s
fi

if [ -f /etc/fstab ]; then
	mount -a
fi
